# Generated by Django 3.2.12 on 2022-02-19 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 18, 24, 25, 878103, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
